<!DOCTYPE html>
<html lang="en-gb">
	<?php 
    	$this->open("head");
			require_once("{$this->partial['header']}");
		$this->close("head");
    	$this->open("body");
    	
    		$this->open("div", "content", "container")
    			->h(1, "Date Picker example", "header")
    			->h(4, "&laquo; This page demonstrates a simple mobile-friendly date-picker with date validation", "sub-header")
    			->text("Here we are using HTML 5 elements and bespoke jQuery/JavaScript", true)
    			->open("hr", '', null, true)
    		->close("div");
    		$this->open("div", "date", "container")
    			->form("date", "", "post", "col-xs-12")
    				->p()->class("col-xs-12 col-md-4 pull-left")->closeElement()
    					->select("day", "day", "col-xs-12", $this->days, '', true)
    				->close("p")
    				->p()->class("col-xs-12 col-md-4 pull-left")->closeElement()
    					->select("month", "month", "col-xs-12", $this->months, '', true)
    				->close("p")
    				->p()->class("col-xs-12 col-md-4 pull-left")->closeElement()
    					->select("year", "year", "col-xs-12", $this->years, '', true)
    				->close("p")
    				->p()->class("col-xs-12 col-md-4 pull-right")->closeElement()
    					->input()->id("submit")->name("sumbit")->type("sumbit")->value("Sumbit &raquo;")->class("col-xs-12 col-md-2 pull-right btn btn-submit")->closeElement(true)
    				->close("p")
    			->close("form")
    		->close("div");
    		require_once("{$this->partial['footer']}");
    	
    	$this->close("body");
    ?>
</html>