<footer id="footer" class="container">
	<div class="col-xs-12 clearfix">
		<h5 class="text-centre clearfix"><a href="https://github.com/sbebbers/FrameWork.php#frameworkphp" target="_blank">FrameWork.php</a> &copy; 2016 - <?php echo date('Y'); ?> Donkeysoft</h5>
		<h6 class="text-centre clearfix">With help, support and development input from Linden Bryon, continued development thanks to Rushcliff Ltd, Staffordshire, UK</h6>
	</div>
	<script type="text/javascript" src="<?php echo $this->host; ?>/js/scripts.js"></script>
	<?php if($this->segment == 'date-example'): ?>
		<script type="text/javascript" src="<?php echo $this->host; ?>/js/date-check.js"></script>
	<?php endif; ?>
	<?php if(getConfig('mode') == "test"): ?>
		<?php
            $this->lib->debug(
                array(
                    'version'           => getConfig('version'),
                    'releaseCandidate'  => (getConfig('rc') === true) ? "true" : "false"
                )
            );
		?>
	<?php endif; ?>
</footer>
