<footer id="footer" class="container">
	<div class="col-xs-12 clearfix">
		<h5 class="text-centre"><a href="https://github.com/sbebbers/FrameWork.php" target="_blank">FrameWork.php</a> &copy; 2016 - <?php echo date('Y'); ?> Donkeysoft</h5>
	</div>
	<script type="text/javascript" src="<?php echo $this->host; ?>/js/scripts.js"></script>
	<?php if($this->segment == 'date-example'): ?>
		<script type="text/javascript" src="<?php echo $this->host; ?>/js/date-check.js"></script>
	<?php endif; ?>
</footer>