<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><?php echo $this->title ?? ''; ?> Shaun Bebbington</title>
<meta name="description" content="<?php echo $this->description ?? 'Skeleton example'; ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<?php if(!empty($this->metaData)): ?><?php echo $this->metaData; ?><?php else: ?>
<meta name="author" content="Change Me" /><!-- Primary author of the website -->
<meta name="twitter" content="@twitter" /><!-- Primary twitter account for the website or author -->
<?php endif; ?>
<?php echo $this->canonical ?? ''; ?>
<script src="//code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<link href="<?php echo $this->host; ?>/css/normalize.css" rel="stylesheet">
<link href="<?php echo $this->host; ?>/css/styles.css" rel="stylesheet">